services:
  db:
    image: postgres:15-alpine
    container_name: webmaderarte-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webmaderarte
    volumes:
      - webmaderarte_postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webmaderarte-app
    restart: always
    ports:
      - "3006:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/webmaderarte?schema=public
      - NEXTAUTH_SECRET=some-very-secret-key-123
      - NEXTAUTH_URL=http://localhost:3006
    depends_on:
      - db

volumes:
  webmaderarte_postgres_data:
